version: '2'

services:
  nginx:
    image: nginx
    volumes:
      - "app-files:/app/web"
      - ./app/config/docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - front
      - back
    ports:
      - "8080:80"
    environment:
      - "PHP_FPM_HOST=php:9000"
      - "PHP_FPM_ROOT_DIR=/app/web"

  db:
    image: mysql:8.0
    volumes:
      - "app-db:/var/lib/mysql:rw"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=restapi
    networks:
      - back

  php:
    build: .
    volumes:
      - "app-files:/app/web"
      - ./log/php-fpm:/var/log/php-fpm
      - ./app/config/docker/php-fpm-7/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./app/config/docker/php-fpm-7/php.ini:/usr/local/etc/php/php.ini
      - .:/app
    networks:
      - back
    depends_on:
      - db

networks:
  front: {}
  back: {}

volumes:
  app-files: {}
  app-db: {}