version: '2'

services:
  nginx:
    image: nginx:latest
    networks:
      - default
    ports:
      - "80:80"
    volumes:
      - ./app/config/docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - .:/app
      - ./log/nginx:/var/log/nginx
  php:
    build: ./app/config/docker/php-fpm-7
    networks:
      - default
    volumes:
      - ./log/php-fpm:/var/log/php-fpm
      - ./app/config/docker/php-fpm-7/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./app/config/docker/php-fpm-7/php.ini:/usr/local/etc/php/php.ini
      - .:/app
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=restapi
    volumes:
      - "db:/var/lib/mysql:rw"
    networks:
      - default
    dns_search:
      - db

networks:
  default: {}

volumes:
  db: {}